### ISSUE TITLE
Replacing a group fails via JamfComputerGroupUploader

### ISSUE THREAD

**Issue by jshirle2** [grahampugh/jamf-upload#42]
When using a computer group name that contains the %version% variable the upload fails if that computer group already exists. 

Here is the very verbose log containing the relevant failures: 

```
{'Input': {'API_PASSWORD': 'API_PASS',
           'API_USERNAME': 'API_USER',
           'JSS_URL': 'JSS_URL',
           '**computergroup_name': 'USS.FIREFOX.ALL.NEEDS.%version%**',
           'computergroup_template': 'USS_UPDATE_GROUP_PM_TEMPLATE.xml',
           'replace_group': True}}
JamfComputerGroupUploader: File found at: /Users/ussadmin/grahampugh-recipes/Jamf_Recipes/USS_UPDATE_GROUP_PM_TEMPLATE.xml
**JamfComputerGroupUploader: Checking for existing 'USS.FIREFOX.ALL.NEEDS.%version%' on JSS_URL**
JamfComputerGroupUploader: No existing cookie found - starting new session
JamfComputerGroupUploader: ("Replacing any instances of 'UPDATE_GROUP_NAME' with", "'USS.FIREFOX.ALL.NEEDS.%version%'")
JamfComputerGroupUploader: ("Replacing any instances of 'SITE' with", "'USS'")
JamfComputerGroupUploader: ("Replacing any instances of 'PATCH_MANAGEMENT_TITLE' with", "'Mozilla Firefox'")
JamfComputerGroupUploader: ("Replacing any instances of 'version' with", "'95.0.2'")
JamfComputerGroupUploader: Computer Group data:
JamfComputerGroupUploader: <?xml version="1.0" encoding="UTF-8"?>
<computer_group>
	<name>USS.FIREFOX.ALL.NEEDS.95.0.2</name>
	<is_smart>true</is_smart>
	<site>
			<name>USS</name>
	</site>	
	<criteria>
		<criterion>
	        <name>Patch Reporting: Mozilla Firefox</name>
			<priority>0</priority>
			<and_or>and</and_or>
			<search_type>less than</search_type>
			<value>95.0.2</value>
			<opening_paren>false</opening_paren>
			<closing_paren>false</closing_paren>
      </criterion>
	</criteria>
</computer_group>
JamfComputerGroupUploader: Uploading Computer Group...
JamfComputerGroupUploader: Computer Group upload attempt 1
JamfComputerGroupUploader: Existing cookie found: APBALANCEID=aws.usw2-std-ellison1-tc-10
JamfComputerGroupUploader: b'<html>\n<head>\n   <title>Status page</title>\n</head>\n<body style="font-family: sans-serif;">\n<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>\n<p>**Error: Duplicate name</p>\n<p>You can get technical details <a href="http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>\nPlease continue your visit at our <a href="/">home page</a>.\n</p>\n</body>\n</html>\n'**
Receipt written to /Users/ussadmin/Library/AutoPkg/Cache/com.github.grahampugh.recipes.jamf.Firefox/receipts/Firefox_Prod.jamf.recipe-receipt-20211221-101336.plist
The following recipes failed:
    **Firefox_Prod.jamf.recipe.yaml
        Error in com.github.grahampugh.recipes.jamf.Firefox: Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader: Error: WARNING: Computer Group 'USS.FIREFOX.ALL.NEEDS.%version%' upload failed due to a conflict**
The following computer groups were created or updated in Jamf Pro:

```

And then here is my full recipe: 

```
Description: |

Identifier: com.github.jshirle2.recipes.jamf.Firefox
MinimumVersion: "2.3"
ParentRecipe: com.github.autopkg.pkg.Firefox_EN

Input:
  NAME: FIREFOX
  SITE: "USS"
  PATCH_MANAGEMENT_TITLE: "Mozilla Firefox"
  PACKAGE_CATEGORY: "USS - EDM - Prod"
  TESTING_CATEGORY: "USS - EDM - Test"
  TESTING_GROUP_NAME: "USS.%NAME%.TESTERS"
  TESTING_GROUP_TEMPLATE: "USS_TESTING_GROUP_TEMPLATE.xml"
  TESTING_POLICY_NAME: "USS.%NAME%.%version%.TEST"
  TESTING_POLICY_TEMPLATE: "USS_TESTING_POLICY_TEMPLATE.xml"
  FUNCTION_POLICY_NAME: "USS.%NAME%.%version%.INSTALL"
  FUNCTION_CATEGORY: "Functions - Apps"
  FUNCTION_POLICY_TEMPLATE: "USS_FUNCTION_POLICY_TEMPLATE.xml"
  UPDATE_GROUP_NAME: "USS.FIREFOX.ALL.NEEDS.%version%"
  UPDATE_GROUP_TEMPLATE: "USS_UPDATE_GROUP_PM_TEMPLATE.xml"
  UPDATE_POLICY_NAME: "USS.%NAME%.UPDATE"
  UPDATE_POLICY_FREQUENCY: "Once every day"
  UPDATE_POLICY_CATEGORY: "Updates"
  UPDATE_POLICY_TEMPLATE_FACSTAFF: "USS_UPDATE_POLICY_FACSTAFF_TEMPLATE.xml"
  UPDATE_POLICY_TEMPLATE_APPLIANCE: "USS_UPDATE_POLICY_APPLIANCE_TEMPLATE.xml"
  SELF_SERVICE_DISPLAY_NAME: "Install %NAME% %version%"
  SELF_SERVICE_DESCRIPTION: "Mozilla Firefox is a free and open source web browser."
  SELF_SERVICE_ICON: "%NAME%.png"
  INSTALL_BUTTON_TEXT: "Install %version%"
  REINSTALL_BUTTON_TEXT: "Install %version%"

Process: 
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments: 
      pkg_category: "%PACKAGE_CATEGORY%"

  - Processor: com.github.grahampugh.recipes.commonprocessors/VersionRegexGenerator

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_name: "%TESTING_GROUP_NAME%"
      computergroup_template: "%TESTING_GROUP_TEMPLATE%"
      replace_group: true

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfComputerGroupUploader
    Arguments:
      computergroup_name: "%UPDATE_GROUP_NAME%"
      computergroup_template: "%UPDATE_GROUP_TEMPLATE%"
      replace_group: true

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments:
      policy_template: "%TESTING_POLICY_TEMPLATE%"
      policy_name: "%TESTING_POLICY_NAME%"
      icon: "%SELF_SERVICE_ICON%"
      replace_policy: true
  
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments: 
      policy_template: "%FUNCTION_POLICY_TEMPLATE%"
      policy_name: "%FUNCTION_POLICY_NAME%"
      replace_policy: true

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
    Arguments: 
      policy_template: "%UPDATE_POLICY_TEMPLATE_FACSTAFF%"
      policy_name: "%UPDATE_POLICY_NAME%.FACSTAFF.LOANERS.SHAREDEMPLOYEELOCAL"
      replace_policy: true
```
