### ISSUE TITLE
create multiple policies with JamfPolicyUploader

### ISSUE THREAD

**Issue by user1233445** [grahampugh/jamf-upload#95]
Hi Guys,

I'm trying to create one jamf recipe, which creates one jamf patch policy and two normal policies. Is it possible to create two policies with one jamf recipe? The reason I ask is that I got an error message as soon as I add the second JamfPolicyUploader:

`The following recipes failed:
    local.jamf.RocketChat
        Error in local.jamf.RocketChat: Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader: Error: 'NoneType' object has no attribute 'startswith'` 

The processors in my recipe:
```
- Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
  Arguments:
    provisioning_policy_name: '%PROVISIONING_POLICY_NAME%'
    provisioning_trigger: '%PROVISIONING_TRIGGER%'
    provisioning_category: '%PROVISIONING_CATEGORY%'
    provisioning_policy_template: '%PROVISIONING_POLICY_TEMPLATE%'
    replace_policy: 'true'
```

```
- Processor: com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
  Arguments:
    icon: '%SELFSERVICE_ICON%'
    policy_name: '%SELFSERVICE_POLICY_NAME%'
    selfserivce_category: '%SELFSERVICE_CATEGORY%'
    selfservice_display_name: '%SELFSERVICE_DISPLAY_NAME%'
    selfservice_description: '%SELFSERVICE_DESCRIPTION%'
    selfservice_main_page: '%SELFSERVICE_MAIN_PAGE%'
    selfservice_force_description: '%SELFSERVICE_FORCE_DESCRIPTION%'
    policy_template: '%SELFSERVICE_POLICY_TEMPLATE%'
    replace_policy: 'true'
    replace_icon: 'true'
```

Best regards
